version: "3.2"

services:
  dev_backend_service:
    container_name: dev_backend_service
    build:
      context: ./backend/service
      dockerfile: Dockerfile
      args:
        SERVER_MODE: dev
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
    networks:
      dev_hikingdom_net:
        ipv4_address: 172.21.0.3
  
  dev_backend_batch:
    container_name: dev_backend_batch
    build:
      context: ./backend/batch
      dockerfile: Dockerfile
    args:
      SERVER_MODE: dev
    ports:
      - 8083:8080
    environment:
      - TZ=Asia/Seoul
    networks:
      dev_hikingdom_net:
        ipv4_address: 172.21.0.5

  frontend_dev:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    networks:
      dev_hikingdom_net:
        ipv4_address: 172.21.0.2

networks:
  dev_hikingdom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1