version: "3"
services:
  server-dev:
    container_name: server-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVER_MODE: dev
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
  client-dev:
    container_name: client-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - server-dev